---

- hosts: all
  become: true
  tasks:

 # This is for Redhat and it's derivatives

  - name: Update repository index for RedHat and it's derivatives.
    dnf:
      update_cache: yes
    when: ansible_distribution in ["RedHat", "Rocky"]

  - name: Install Apache and PHP package on RedHat, Rocky or Alma Linux.
    dnf:
      name:
        - httpd
        - php-cli.x86_64  
      state: latest
    when: ansible_distribution in ["RedHat", "Rocky"]

# This is for Debian and Ubuntu

  - name: Update repository index for Debain and Ubuntu.
    apt:
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: Install Apache and PHP package on Debian and Ubuntu Linux.
    apt:
      name: 
        - apache2
        - libapache2-mod-php  
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]


